# Generated by Django 5.2.5 on 2025-08-10 20:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name="ID"
                )),
                ("status", models.CharField(
                    choices=[("PENDING", "Pending"), ("PAID", "Paid")],
                    default="PENDING",
                    max_length=20
                )),
                ("type", models.CharField(
                    choices=[("PAYMENT", "Payment"), ("FINE", "Fine")],
                    max_length=20
                )),
                ("session_url", models.URLField()),
                ("session_id", models.CharField(max_length=255)),
                ("money_to_pay", models.DecimalField(
                    decimal_places=2,
                    default=Decimal("0.00"),
                    max_digits=10
                )),
                ("borrowing", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="payments",
                    to="borrowings.borrowing"
                )),
            ],
        ),
    ]
