# Generated by Django 5.2.5 on 2025-08-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0002_alter_payment_session_id_alter_payment_session_url"
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
